language: node_js   #设置语言
node_js: stable     #设置相应的版本

branches:
  only:
    - master  #只监测这个分支，一有动静就开始构建
notifications:
  email:
    recipients:
      - starrier@starrier.org
      - starriers@starrier.org
    on_success: change # default: change
    on_failure: always # default: always

cache:
  directories:
    - node_modules    #据说可以减少 travis 构建时间
before_install:
  - npm install hexo --save
  - npm install hexo-cli --save
  - npm install gulp-cli --save
install:
  - npm install   #安装hexo及插件
before_script:
  - git clone --branch master https://github.com/Starrier/starrier.github.io.git
script:
  - hexo clean
  - hexo g
  - gulp
after_success:
  - cd ./public
  - git init
  - git config user.name "Starrier"   #修改成自己的github用户名
  - git config user.email "starrier@starrier.org"   #修改成自己的GitHub邮箱
  - git add .
  - git commit -m "update by Travis-CI"
  - git checkout -b gh-pages
  - git push --force -u https://${GH_TOKEN}@${GH_REF} gh-pages #GH_token就是在travis中设置的token

env:
  global:
    - GH_REF=github.com/Starrier/starrier.github.io.git
