language: node_js   #设置语言
node_js: stable     #设置相应的版本
cache:
  directories:
    - node_modules    #据说可以减少travis构建时间
before_install:
  - npm install hexo --save
  - npm install hexo-cli --save
install:
  - npm install   #安装hexo及插件
before_script:
  - npm install -g mocha
  - git clone --branch master https://github.com/Starrier/starrier.github.io.git
script:
  - hexo cl   #清除
  - hexo g   #生成
after_script:
  - cd ./public
  - git init
  - git config user.name "Starrier"   #修改成自己的github用户名
  - git config user.email "starrier@starrier.org"   #修改成自己的GitHub邮箱
  - git add .
  - git commit -m "update by Travis-CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master #GH_token就是在travis中设置的token
branches:
  only:
    - master  #只监测这个分支，一有动静就开始构建
env:
  global:
    - GH_REF=https://github.com/Starrier/starrier.github.io.git
